# Generated by Django 3.2.7 on 2021-09-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
